mbta/mobile_app_backend

config/test.exs
lib/mbta_v3_api/store.ex
lib/mbta_v3_api/store/predictions.ex
lib/mbta_v3_api/supervisor.ex
test/mbta_v3_api/store/predictions_test.exs

Summary
Ticket: [Predictions Scalability: new channel that publishes predictions updates in chunks](https://app.asana.com/0/1205732265579288/1207791938443975/f)
This PR adds only the functionality for reading + writing predictions to the ETS store. The functionality for actually using this ETS table is underway in https://github.com/mbta/mobile_app_backend/pull/186.

feat(Store.Predictions): Add support for writing + reading predictions

---

.vscode/launch.json
.vscode/tasks.json

_Ticket:_ No ticket
I put these together last time I was working on the backend, partly for ease of running and keybinding basic commands from the editor, but also because running through the Code runner vs a regular terminal gives easy access to log filtering, and that's really helpful when doing local debugging, since the backend logs are painfully noisy.
Not sure if anyone else on the team even uses VS Code, and if we don't think this is appropriate to include in the repo, I'll just change this PR to put it in `.gitignore` (though if my computer dies at some point, it would then be annoying to have to get them working again).

util: Add VS Code configs for running mix tasks

---

lib/mbta_v3_api/stream/instance.ex
lib/mobile_app_backend/application.ex
lib/mobile_app_backend/finch_pool_health.ex
test/mobile_app_backend/finch_pool_health_test.exs

No ticket, but identified as an observability improvement while working on 
[Predictions Scalability: new channel that publishes predictions updates in chunks](https://app.asana.com/0/1205732265579288/1207791938443975/f). 
We suspect there are some issues with request pooling based on unexpectedly slow req response logs under load testing. This will help us identify if that is the case ([slack thread](https://mbta.slack.com/archives/GP5QJM98A/p1726249147438039))

feat: log finch pool health stats periodically

---

lib/mobile_app_backend_web/controllers/schedule_controller.ex
lib/util.ex
test/mobile_app_backend_web/controllers/schedule_controller_test.exs

_Ticket:_ [Fetch schedules for the entire current service day](https://app.asana.com/0/1205732265579288/1208252548197533/f)
Remove the time filtering on the schedules request. Confirmed that the frontend handles this fine on latest `main` and doesn't display scheduled trips in the past.

feat: Fetch schedules for the entire current service day

---

lib/mbta_v3_api/stream/instance.ex
test/mbta_v3_api/stream/instance_test.exs

_Ticket:_ none
Fixes [serious data loss if an alert fails to parse](https://mbta.slack.com/archives/C05QMG9GS9M/p1726693649005009?thread_ts=1726688749.388879&cid=C05QMG9GS9M).

fix: restart ServerSentEventStage if Stream.Consumer crashes

---

lib/mbta_v3_api/store.ex
lib/mbta_v3_api/store/predictions.ex
lib/mbta_v3_api/stream/static_instance.ex
lib/mobile_app_backend/predictions/pub_sub.ex
test/mbta_v3_api/store/predictions_test.exs
test/mobile_app_backend/predictions/pub_sub_test.exs
test/mobile_app_backend_web/channels/predictions_for_stops_v2_channel_test.exs

_Ticket:_ [Predictions Scalability: new channel that publishes predictions updates in chunks](https://app.asana.com/0/1205732265579288/1207791938443975/f)
This PR publishes trips associated with predictions by stop. Associated vehicles to follow in a separate PR

feat(Predictions.PubSub): publish related trip data

---

config/test.exs
lib/mbta_v3_api/store.ex
lib/mbta_v3_api/store/predictions.ex
lib/mbta_v3_api/store/vehicles.ex
lib/mbta_v3_api/stream/instance.ex
lib/mbta_v3_api/stream/static_instance.ex
lib/mbta_v3_api/supervisor.ex
lib/mobile_app_backend/predictions/pub_sub.ex
lib/mobile_app_backend/predictions/stream_subscriber.ex
test/mbta_v3_api/store/predictions_test.exs
test/mbta_v3_api/store/vehicles_test.exs
test/mbta_v3_api/store_test.exs
test/mbta_v3_api/stream/static_instance_test.exs
test/mobile_app_backend/predictions/pub_sub_test.exs
test/mobile_app_backend/predictions/stream_subscriber_test.exs
test/mobile_app_backend_web/channels/predictions_for_stops_v2_channel_test.exs
test/test_helper.exs

_Ticket:_ [Predictions Scalability: new channel that publishes predictions updates in chunks](https://app.asana.com/0/1205732265579288/1207791938443975/f)
This PR adds a new Vehicle store that is updated by a single stream for all vehicles. 
Those vehicles are fetched as part of fetching predictions for parity with the existing predictions channel.

feat(Predictions.PubSub): Include related vehicles

---

config/config.exs
lib/mobile_app_backend/application.ex
lib/mobile_app_backend/global_data_cache.ex
lib/mobile_app_backend_web/controllers/global_controller.ex
test/mobile_app_backend/global_data_cache_test.exs
test/mobile_app_backend_web/controllers/global_controller_test.exs

_Ticket:_ [Cache global data in backend instead of recomputing on demand](https://app.asana.com/0/1205732265579288/1208354000423233/f)
Stores the global data in `:persistent_term` and refreshes it every five minutes. Per the persistent_term docs, we don't need to check if the new data is the same as the old data, because it'll be ignored automatically if it's the same.

feat: cache global data instead of recomputing on demand

---

lib/mbta_v3_api/store/predictions.ex
test/mbta_v3_api/store/predictions_test.exs

Follow up from https://github.com/mbta/mobile_app_backend/pull/198 with an edge case I hadn't tested.
I was re-running load testing and noticed the avg message size for `stream_data` was greater than the avg message size for the join response.
When there are no vehicles associated with any predictions for a stop (or there were no predictions at all), the full set of vehicles would be returned. This guards against that by not fetching any vehicles when there are no vehicle Ids for the list of predictions. Adds a guard for trips too for safe measure.

fix(Store.Predictions): If there are no associated vehicles, return no vehicles

---

test/mbta_v3_api/mbta_v3_api_test.exs
test/mbta_v3_api/stream/consumer_test.exs
test/mobile_app_backend/throttler_test.exs

_Ticket:_ [Fix flaky backend data streaming tests](https://app.asana.com/0/1206699228703698/1206951180399064/f)
Turns out, if you mention a flaky test you don't care enough to also fix, you are invoking it.
If these were this easy the whole time, I feel really silly for not just fixing them in March.

test: fix some flaky tests

---

.github/workflows/ci.yml
config/test.exs
lib/mobile_app_backend/application.ex
lib/mobile_app_backend/global_data_cache.ex
lib/mobile_app_backend_web/controllers/global_controller.ex
test/mobile_app_backend/global_data_cache_test.exs
test/mobile_app_backend_web/controllers/global_controller_test.exs
test/test_helper.exs

No ticket, a fix found in https://github.com/mbta/mobile_app_backend/pull/206
This ensures that the global data cache will periodically check for updated data from the V3 API. Since this involves making a network request shortly after application startup, this also ensures that the docker build has the V3 API URL configured and that it can be skipped during testing.

fix(GlobalDataCache): trigger timed fetch on startup

---

lib/mbta_v3_api/store/predictions.ex

Fix for [Predictions Scalability: new channel that publishes predictions updates in chunks](https://app.asana.com/0/1205732265579288/1207791938443975/f)
A possible fix for[ this sentry error
](https://mbtace.sentry.io/issues/5917860189/?project=4506321052172288), where the client received data for a prediction without a corresponding trip. This could happen if they received data after the predictions were inserted into ETS before trips. Thanks to @boringcactus for the suggestion for the simple solution to this: insert trips before predictions.

fix(Store.Predictions): insert trips before predictions

---

.tool-versions
lib/mobile_app_backend_web/channels/vehicles_for_route_channel.ex
test/mobile_app_backend_web/channels/vehicles_for_route_channel_test.exs

_Ticket:_ [Green Line vehicles don't load in filtered Stop Details](https://app.asana.com/0/1205732265579288/1207813918309501/f)
For the grouped green line stop pages, we need to connect to a vehicles channel that can return multiple routes at once, but the existing one only supports a single route ID. This adds a new channel which accepts any number of route IDs and returns all vehicles matching them.

feat: Add new multi-route vehicles channel

---

lib/mbta_v3_api/store/predictions.ex
test/mbta_v3_api/store/predictions_test.exs

_Ticket:_ In support of  [Predictions crash due to missing trip](https://app.asana.com/0/1205425564113216/1208510328404939/f)
One possible reason that clients are experiencing missing trips is that the trip could be removed from the ETS store prematurely. By logging when trips & predictions are removed from the store, we can better understand if trips are removed before their corresponding predictions in the backend or if this is a frontend issue.

chore(Store.Predictions): Add log when record removed for debugging

---

.github/workflows/ci.yml

No ticket, currently blocking merging fixes like https://github.com/mbta/mobile_app_backend/pull/217.
As @boringcactus pointed out, likely related to `ubuntu-latest` bump from 22.04 to 24.04

chore: disable code coverage reporting

---

lib/mbta_v3_api/store/predictions.ex
test/mbta_v3_api/store/predictions_test.exs

_Ticket:_ [Predictions crash due to missing trip](https://app.asana.com/0/1205425564113216/1208510328404939/f)
This fixes a bug due to trips being included in the prediction stream for multiple routes, for multi-route trips (SL, some CR, GL added trips, and others. See [full investigation](https://www.notion.so/mbta-downtown-crossing/Missing-Trip-Crash-120f5d8d11ea80ce9537e9e6102881ab)).
This adds a simple measure to only delete a trip record if there are no associated predictions for that trip. Note: as far as I can tell, the trip record from different route streams would all share a route ID, and not necessarily match the route of the associated prediction, so this doesn't try to factor route ID into knowing when to delete a trip record.

fix(Store.Predictions): Only remove trips if there are no other predictions

---

lib/mbta_v3_api/route_pattern.ex
lib/mobile_app_backend_web/controllers/shapes_controller.ex
test/mbta_v3_api/route_pattern_test.exs
test/mobile_app_backend_web/controllers/shapes_controller_test.exs

_Ticket:_ [Fix: Newburyport branch isn't drawn on map](https://app.asana.com/0/1205732265579288/1208493978668470/f)
Checked locally that this causes Newburyport to be drawn correctly, and checked with `dbg/2` that nothing else will be newly included or excluded as a result of this change.

fix: draw less-typical canonical patterns on map

---

config/config.exs
config/test.exs
lib/mbta_v3_api/stream/static_instance.ex
lib/mobile_app_backend/application.ex
lib/mobile_app_backend/vehicles/pub_sub.ex
lib/mobile_app_backend/vehicles/registry.ex
lib/mobile_app_backend_web/channels/predictions_for_stops_v2_channel.ex
lib/mobile_app_backend_web/channels/vehicle_channel.ex
lib/mobile_app_backend_web/channels/vehicles_for_route_channel.ex
load_testing/locustfile.py
test/mobile_app_backend/vehicles/pub_sub_test.exs
test/mobile_app_backend_web/channels/vehicle_channel_test.exs
test/mobile_app_backend_web/channels/vehicles_for_route_channel_test.exs
test/test_helper.exs

_Ticket:_ [[Name](https://app.asana.com/0/1205732265579288/1208619681848095/f)](https://app.asana.com/0/1205732265579288/1208619681848095/f)
Addresses the bottleneck found in Load Testing when many users are joining vehicles channels at once. 
`Vehicles.PubSub` is largely a copy of `Predictions.PubSub` - there is probably a good basis for extracting out common pieces, but I think it is worth saving that for a separate ticket. 
This does switch `VehicleChannel` to use PubSub as well for consistency.
Testing:
* Added & updated unit tests
* Ran locally on phone pointing to dev-orange deployiment
* Confirmed logs for new PubSub module in Splunk as expected

perf(VehiclesForRouteChannel): Use vehicles from PubSub instead of GenServer

---

load_testing/locustfile.py

No ticket - small fix to https://github.com/mbta/mobile_app_backend/pull/224.
Load tests run from Github Actions were failing because of invalid date format [here](https://github.com/mbta/mobile_app_backend/actions/runs/11520245289/job/32071109640#step:12:528). Setting the timezone to America/New_York resolves the issue, as confirmed by [this passing run](https://github.com/mbta/mobile_app_backend/actions/runs/11521337677).

fix(load_testing): Set timezone to America/New_York

---

lib/mobile_app_backend_web/controllers/schedule_controller.ex
test/mobile_app_backend_web/controllers/schedule_controller_test.exs

_Ticket:_ [Fix schedule request with no stops](https://app.asana.com/0/1205732265579288/1208436662720170/f)
Tested this locally and the error banner no longer appears when outside the service area.

fix: return no schedules for no stops

---

lib/mobile_app_backend_web/channels/predictions_for_stops_v2_channel.ex
test/mobile_app_backend_web/channels/predictions_for_stops_v2_channel_test.exs

_Ticket:_ none
Fixes the frontend getting stuck loading when outside the service area.

fix: gracefully handle predictions v2 for empty stop list

---

load_testing/locustfile.py

No ticket, updates while testing for https://github.com/mbta/mobile_app_backend/pull/231
This makes load testing more realistic in a few ways:
* Represents caching of global + map rail shape data, assumes 80% of users have that data cached from the start
* Fetches data for only stations or stops, never child stops within stations
* Fetches schedules from nearby transit
* Longer max wait interval between tasks
* Picks fewer nearby stops & stations (max 15 instead of max 28)

feat(locustfile): More realistic usage patterns

---

config/prod.exs

_Ticket:_ [backend health monitoring](https://app.asana.com/0/1205732265579288/1207910202706561/f)
This was added in other applications which use `diskusage_logger`, currently no `diskusage_report` logs are being written by the backend, and this looks like the reason why.

fix: Get diskusage_logger functional

---

config/config.exs
config/test.exs
lib/mbta_v3_api/store/alerts.ex
lib/mbta_v3_api/stream/static_instance.ex
lib/mbta_v3_api/supervisor.ex
lib/mobile_app_backend/alerts/pub_sub.ex
lib/mobile_app_backend/alerts/registry.ex
lib/mobile_app_backend/application.ex
lib/mobile_app_backend_web/channels/alerts_channel.ex
test/mbta_v3_api/store/alerts_test.exs
test/mobile_app_backend/alerts/pub_sub_test.exs
test/mobile_app_backend/predictions/pub_sub_test.exs
test/mobile_app_backend_web/channels/alerts_channel_test.exs
test/test_helper.exs

_Ticket:_ [Remove alert streaming bottleneck](https://app.asana.com/0/1205732265579288/1208690341598921/f)
This PR moves from storing the state of alerts in a GenServer to storing it in an ETS so that subscribers can read in parallel. Updates are published to subscribers every 0.5 seconds.
I timeboxed doing some reduction of code duplication here using a macro, but couldn't quite get it to work and the duplication seems minimal enough to not block getting this change out over.

feat(AlertsChannel): Subscribe to PubSub instead of reading from GenServer

---

lib/mbta_v3_api/repository_cache.ex

No ticket, follow up to https://github.com/mbta/mobile_app_backend/pull/247. 
@boringcactus [pointed out in slack ](https://mbta.slack.com/archives/C05QMG9GS9M/p1732562811606739?thread_ts=1732561776.880189&cid=C05QMG9GS9M) that the previous fix doesn't entirely eliminate the possibility of cache collisions. We can prevent them entirely by including the entire contents of args without hashing them. Based on splunk results for our existing queries, the longest expected value for inspect(args) is 891.

feat(RepositoryCache): No hashing in cache key

---

lib/mbta_v3_api/store/alerts.ex

No ticket. Hotfix to address GL alert boundary issue at Park St [discussed in Slack](https://mbta.slack.com/archives/C03K6NLKKD1/p1733499406012269).
Removes unnecessary affected entities that are causing the app to show a Westbound suspension at Park St, when really there is only an Eastbound suspension.
Before & after:

tmp(Alerts.Store): Override GL diversion informed entities

---

lib/mobile_app_backend/mapbox_token_rotator.ex
test/mobile_app_backend/mapbox_token_rotator_test.exs

No ticket. Short circuit mapbox errors that are causing repeated crashes by simply returning a dummy token. 
Commented out broken tests, ran `mix phx.server` locally to confirm server starts up and is stable.

hotfix: dummy mapbox token rotator

---

lib/mobile_app_backend/mapbox_token_rotator.ex
test/mobile_app_backend/mapbox_token_rotator_test.exs

This reverts commit 4ab0acf95b876499aa89a580bf24ade65eaf5233.
No ticket. Revert PR for https://github.com/mbta/mobile_app_backend/pull/278 so that it is ready when we have a corrected mapbox config.

Revert "hotfix: dummy mapbox token rotator (#278)"

---

lib/mbta_v3_api/alert.ex
lib/mobile_app_backend/alerts/pub_sub.ex
lib/mobile_app_backend_web/channels/alerts_channel.ex
lib/mobile_app_backend_web/channels/user_socket.ex
test/mobile_app_backend/alerts/pub_sub_test.exs
test/mobile_app_backend_web/channels/alerts_channel_test.exs

_Ticket:_ [Update backend to handle new alert causes/effects](https://app.asana.com/0/1205732265579288/1209561344386983)
[Frontend PR](https://github.com/mbta/mobile_app/pull/814)
This creates a new `alerts:v2` channel which will serve alerts containing the causes which were newly added in this PR.
The existing `alerts` channel now replaces any of these causes with `:unknown_cause`, not doing so would cause any <=1.2.0 versions of the app to break entirely if an alert with one of these causes existed in the feed.
Added unit tests for the new alert behavior, and did some manual testing connected to the app, ensuring that when it was pointed at each channel it either did or didn't contain the new causes.

feat: Add a new alert channel with new causes

---

lib/mbta_v3_api/alert.ex
test/mbta_v3_api/alert_test.exs

_Ticket:_ [Alert Details | format later today & start/end of service](https://app.asana.com/0/1205732265579288/1208572284247951)
Adds a new enum field to alerts which tells us how much we should trust the provided active period.

feat: Add duration_certainty field to Alerts

---

lib/mbta_v3_api/alert.ex
test/mbta_v3_api/alert_test.exs

_Ticket:_ [Display subway delays](https://app.asana.com/0/1205732265579288/1208643635656244/f)
* Expose alert severity so that we can use it to determine which subway delays to show

feat(Alert): Include severity attribute

---

lib/mbta_v3_api/store/alerts.ex

_Ticket:_ No ticket
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1744143556538009)
This alert is necessary to work around some strange service realities that would cause RTR to generate invalid predictions. It would show up to riders as a duplicate of the proper user facing alert though, so we're suppressing it.

tmp(Alerts.Store): Remove RTR functionality alert

---

lib/mobile_app_backend_web/controllers/route_controller.ex
lib/mobile_app_backend_web/router.ex
test/mobile_app_backend_web/controllers/route_controller_test.exs

_Ticket:_ [Favorites | Route details - ordered list of stops endpoint](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209816289542478?focus=true)
Add a new endpoint `/api/route/stops` which returns a list of stop ids for each of the stops served along that route. This list will include stops that are only on uncommon route patterns or on different branches, ordered in a sort of coherent way (which is determined by the v3 API).

feat: Add route stops endpoint

---

priv/static/robots.txt

No ticket
Follows the request from this[ slack thread](https://mbta.slack.com/archives/G01E809HUF2/p1748528790162219) pointing to the Sentry doc for [disabling automatic uptime detection ](https://docs.sentry.io/product/alerts/uptime-monitoring/automatic-detection/#disabling-automatic-detection). 
Will merge pending further discussion as to whether this is needed on a project-by-project basis.

chore: disable SentryUptimeBot

---

lib/mobile_app_backend/search/algolia/query_payload.ex
lib/mobile_app_backend_web/controllers/search_controller.ex
lib/mobile_app_backend_web/router.ex
test/mobile_app_backend/search/algolia/query_payload_test.exs
test/mobile_app_backend_web/controllers/search_controller_test.exs

_Ticket:_ [🤖 | Favorites | Add stops flow - search / filter](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210229155855234?focus=true)
This returns a max of 50 results to use to filter the list of displayed routes on the route picker page. The top level search only returns a max of 5 route results.

feat: Add route filter search endpoint

---

lib/mobile_app_backend/search/algolia/query_payload.ex
test/mobile_app_backend/search/algolia/query_payload_test.exs

_Ticket:_ [Favorites | QA | route search](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210826290372839?focus=true)
Filtering by route type in Algolia is not currently possible since route types aren’t set up as a facet, but even if they were, that wouldn’t let us distinguish SL buses from non-SL buses; we’d need to add a new `isSilverLine` property on all the routes as they go into the index, and then we’d need to set that property as a facet as well. Filtering by route type in the `SearchController` would also not be able to distinguish SL routes. The frontend already knows which routes are on the SL page, so I think it makes the most sense to just return every single search result from the backend and let the frontend continue to filter based on which routes are …

fix: return all route search results

---

lib/mix/tasks/check_route_branching.ex
lib/mobile_app_backend/route_branching.ex
lib/mobile_app_backend/route_branching/stop_disambiguation.ex
lib/mobile_app_backend/route_branching/stop_graph.ex
lib/mobile_app_backend/route_branching/workarounds.ex
test/mobile_app_backend/route_branching/stop_disambiguation_test.exs
test/mobile_app_backend/route_branching_test.exs

_Ticket:_ none
Fixes the three cases in the upcoming rating where route branching fails. Also deletes most of the remaining workarounds.

fix: improve route branching looping handling

---

load_testing/locustfile.py

_Ticket:_ none
I get a lot of spam about the [low-intensity load test that runs every three days](https://github.com/mbta/mobile_app_backend/actions/workflows/trivial-load-test.yml) failing, and after some investigation, it fails because the empty string is not a valid API key and so the API will 403 if the API key is set to the empty string, which is set by default. Defaulting to `None` instead causes no API key to be sent, which for low user counts is fine.

fix(load_testing): don’t use empty string as default API key

---

config/prod.exs

_Ticket:_ [[algolia - use prod indices in prod]](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210967667899897?focus=true)
We've been using the test indices in prod this whole time. This switches over the prod config to use the prod ones, now we should be more free to make test changes on the test environment.

fix: Use prod algolia indices

---

lib/mobile_app_backend/route_branching/workarounds.ex

_Ticket:_ none
[Slack thread](https://mbta.slack.com/archives/C05QMG9GS9M/p1755284280045719)
Even if this is something that can be fixed in the API without much hassle, it’s probably worth having a fix in place here in the short term.

fix: add workaround for 15 inbound stop ID list

---

lib/mobile_app_backend_web/controllers/deep_link_controller.ex
lib/mobile_app_backend_web/router.ex
test/mobile_app_backend_web/controllers/deep_link_controller_test.exs

_Ticket:_ [Add campaign tracking to T-alerts CTA on bus delay alerts](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210919282215092?focus=true)
Add a new `go.mbta.com/t-alert` endpoint, which will deeplink into the app if on a device with the app already installed, or redirect to the dotcom `app-store` endpoint if not, including the T Alerts link campaign params so that we can tell when users are installing the app from that link.
After this is deployed, we'll need a follow up alerts-concierge change to update the URL. This also does not include GA events within the app if opened with a deep link (see [ticket](https://app.asana.com/1/15492006741476/project/1205425564113216/task/1211066386453647?focus=true)).

feat: Add T-Alert URL campaign tracking params

---

config/config.exs
lib/mobile_app_backend/application.ex
lib/mobile_app_backend/health/cache.ex
lib/mobile_app_backend/search/algolia/api.ex
lib/mobile_app_backend/search/algolia/cache.ex
mix.exs
test/mobile_app_backend/health/cache_test.exs
test/mobile_app_backend/search/algolia/api_test.exs
test/mobile_app_backend_web/controllers/schedule_controller_test.exs

_Ticket:_ [Cache Algolia results](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1210967667899895?focus=true)
I’m not sure if we’d be interested in also logging the hit rates on our other caches, but I’ve designed the health check to allow for that if we decide we want it.

feat: cache search results

---

lib/mobile_app_backend_web/controllers/deep_link_controller.ex
test/mobile_app_backend_web/controllers/deep_link_controller_test.exs

_Ticket:_ No ticket
The TAlerts CTA link is not properly tracking the campaign when it redirects to dotcom, though based on Splunk logs, we are getting traffic to it with the params set here. This is an attempt to fix it at least for Android, other GA campaign URLs on dotcom seem to follow this format. It's also not working for iOS though, which is surprising because those params seem definitely correct.

fix: Update TAlerts CTA campaign params

---

lib/mobile_app_backend/notifications/subscription.ex
lib/mobile_app_backend/notifications/write_payload.ex
lib/mobile_app_backend/user.ex
lib/mobile_app_backend_web/controllers/notification_subscriptions_controller.ex
lib/mobile_app_backend_web/router.ex
priv/repo/migrations/20250915170809_alter_notifications_on_delete.exs
test/mobile_app_backend_web/controllers/notification_subscriptions_controller_test.exs
test/support/notifications_factory.ex

_Ticket:_ [Notifications | Endpoint for managing subscriptions](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1211139143764269?focus=true)
I think if we want the frontend to maintain all the state and just sync it to the backend as needed, we don’t need separate create/update/delete endpoints and we can just have a “set my list of subscriptions” endpoint. Conveniently, [`Ecto.Changeset.put_assoc/4`](https://hexdocs.pm/ecto/3.13.2/Ecto.Changeset.html#put_assoc/4) makes it easy to set the entire list of associated objects, automatically deleting anything that’s no longer included.

feat: endpoint to manage notification subscriptions
